/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inmobiliaria.bd;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Alquileres extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Alquileres.class.getName());

    /**
     * Creates new form Alquileres
     */
    public Alquileres() {
        initComponents();
        cargarTablaPropiedades();
    }

    private void cargarTablaPropiedades() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //bloqueamos la edicion de texto en toda la tabla
                return false;
            }
        };
        modelo.addColumn("ID Propiedad");
        modelo.addColumn("Dirección");
        modelo.addColumn("Tipo");
        modelo.addColumn("Zona");
        modelo.addColumn("Valor Mensual ($)");

        // Le asignamos este modelo vacio pero con titulos a la tabla
        tablaPropiedades.setModel(modelo);

        // consulta SQL (1 significa True/Disponible)
        String sql = "SELECT p.id_Prop, p.direccion_Prop, t.descripcionTipo, z.nombre_Z, p.valor_Prop "
                + "FROM propiedades p, tipos_propiedad t, zonas z "
                + "WHERE p.cod_Tipo_Prop = t.cod_Tipo_Prop "
                + "AND p.nro_Zona_Ubicada = z.nro_Z "
                + "AND p.en_Alquiler = 1";
        try {
            //conectamos a MariaDB usando tu clase Conexion
            Connection con = Conexion.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            // Recorremos los resultados y agregamos filas a la tabla
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("p.id_Prop");
                fila[1] = rs.getString("p.direccion_Prop");
                fila[2] = rs.getString("t.descripcionTipo");
                fila[3] = rs.getString("z.nombre_Z");
                fila[4] = rs.getFloat("p.valor_Prop");

                modelo.addRow(fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las propiedades: " + ex.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnVolver1 = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tablaPropiedades = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnCrearContrato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnContratos = new javax.swing.JButton();
        fondoborroso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(this::btnVolver1ActionPerformed);
        jPanel2.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        tablaPropiedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scroll.setViewportView(tablaPropiedades);

        jPanel2.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 470, 330));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alquileres Disponibles");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        btnCrearContrato.setText("Crear Contrato de Alquiler");
        btnCrearContrato.addActionListener(this::btnCrearContratoActionPerformed);
        jPanel2.add(btnCrearContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Si quiere registrar un alquiler seleccione la propiedad");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        btnContratos.setText("CONTRATOS");
        jPanel2.add(btnContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        fondoborroso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        jPanel2.add(fondoborroso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        Inmobiliaria menuPrincipal = new Inmobiliaria();
        menuPrincipal.setLocationRelativeTo(null);
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaPropiedades.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, seleccione una propiedad de la tabla antes de crear el contrato.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Para continuar con el contrato se le pedira\n el ingreso del inquilino y del escribano");


            int idPropiedad = (int) tablaPropiedades.getValueAt(filaSeleccionada, 0);
            float valorMensual = (float) tablaPropiedades.getValueAt(filaSeleccionada, 4);

            JOptionPane.showMessageDialog(this, "Para continuar con el contrato se le pedira\n el ingreso del inquilino y del escribano");

            IngresoInquilino ventanaInquilino = new IngresoInquilino(idPropiedad, valorMensual);
            ventanaInquilino.setLocationRelativeTo(null);
            ventanaInquilino.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnCrearContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Alquileres().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContratos;
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel fondoborroso1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaPropiedades;
    // End of variables declaration//GEN-END:variables
}
