/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inmobiliaria.bd;

/**
 *
 * @author maria
 */
public class IngresoInquilino extends javax.swing.JPanel {

    /**
     * Creates new form IngresoInquilino
     */
    public IngresoInquilino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNombreInquilino = new javax.swing.JTextField();
        textDireccionInquilino = new javax.swing.JTextField();
        textTelefonoInquilino = new javax.swing.JTextField();
        textDniInquilino = new javax.swing.JTextField();
        textTelefonoInquilino1 = new javax.swing.JTextField();
        btnCargarInquilino = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Datos del Inquilino");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre y  Apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DNI:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono/s:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 20));

        textNombreInquilino.addActionListener(this::textNombreInquilinoActionPerformed);
        add(textNombreInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 230, -1));

        textDireccionInquilino.addActionListener(this::textDireccionInquilinoActionPerformed);
        add(textDireccionInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 230, -1));

        textTelefonoInquilino.addActionListener(this::textTelefonoInquilinoActionPerformed);
        add(textTelefonoInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, -1));

        textDniInquilino.addActionListener(this::textDniInquilinoActionPerformed);
        add(textDniInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 230, 20));

        textTelefonoInquilino1.addActionListener(this::textTelefonoInquilino1ActionPerformed);
        add(textTelefonoInquilino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 230, -1));

        btnCargarInquilino.setText("Cargar Inquilino");
        btnCargarInquilino.addActionListener(this::btnCargarInquilinoActionPerformed);
        add(btnCargarInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        jLabel1.setText("  ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -100, 550, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreInquilinoActionPerformed

    private void textDireccionInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionInquilinoActionPerformed

    private void textTelefonoInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoInquilinoActionPerformed

    private void textDniInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniInquilinoActionPerformed

    private void btnCargarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarInquilinoActionPerformed

    private void textTelefonoInquilino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoInquilino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoInquilino1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarInquilino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textDireccionInquilino;
    private javax.swing.JTextField textDniInquilino;
    private javax.swing.JTextField textNombreInquilino;
    private javax.swing.JTextField textTelefonoInquilino;
    private javax.swing.JTextField textTelefonoInquilino1;
    // End of variables declaration//GEN-END:variables
}
