/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inmobiliaria.bd;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author maria
 */
public class IngresoEscribano extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresoEscribano.class.getName());

    /**
     * Creates new form IngresoEscribano
     */
    private int idPropiedadSeleccionada;
    private float valorMensualPropiedad;
    private long dniInquilino;

    public IngresoEscribano() {
        initComponents();
    }

    public IngresoEscribano(int idPropiedadSeleccionada, float valorMensualPropiedad, long dniInquilino) {
        initComponents();
        this.idPropiedadSeleccionada = idPropiedadSeleccionada;
        this.valorMensualPropiedad = valorMensualPropiedad;
        this.dniInquilino = dniInquilino;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textDniEscribano = new javax.swing.JTextField();
        textNombreEscribano = new javax.swing.JTextField();
        textDireccionEscribano = new javax.swing.JTextField();
        textTelefonoEscr2 = new javax.swing.JTextField();
        textNroMatriculaEscr4 = new javax.swing.JTextField();
        textTelofonoEscr = new javax.swing.JTextField();
        btnCargaEscribano = new javax.swing.JButton();
        btnEcribanoExistente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Escribano");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Datos del Escribano");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nro de Matricula:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre y  Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono/s:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, 20));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DNI:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 20));

        textDniEscribano.addActionListener(this::textDniEscribanoActionPerformed);
        jPanel1.add(textDniEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, -1));

        textNombreEscribano.addActionListener(this::textNombreEscribanoActionPerformed);
        jPanel1.add(textNombreEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, -1));

        textDireccionEscribano.addActionListener(this::textDireccionEscribanoActionPerformed);
        jPanel1.add(textDireccionEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, -1));

        textTelefonoEscr2.addActionListener(this::textTelefonoEscr2ActionPerformed);
        jPanel1.add(textTelefonoEscr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, -1));

        textNroMatriculaEscr4.addActionListener(this::textNroMatriculaEscr4ActionPerformed);
        jPanel1.add(textNroMatriculaEscr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, -1));

        textTelofonoEscr.addActionListener(this::textTelofonoEscrActionPerformed);
        jPanel1.add(textTelofonoEscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 250, -1));

        btnCargaEscribano.setText("Cargar Escribano");
        btnCargaEscribano.addActionListener(this::btnCargaEscribanoActionPerformed);
        jPanel1.add(btnCargaEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        btnEcribanoExistente.setText("Escribano Existente");
        jPanel1.add(btnEcribanoExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -90, 510, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDniEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniEscribanoActionPerformed

    private void textNombreEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreEscribanoActionPerformed

    private void textDireccionEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionEscribanoActionPerformed

    private void textTelefonoEscr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoEscr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoEscr2ActionPerformed

    private void textNroMatriculaEscr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNroMatriculaEscr4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNroMatriculaEscr4ActionPerformed

    private void textTelofonoEscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelofonoEscrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelofonoEscrActionPerformed

    private void btnCargaEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaEscribanoActionPerformed

        String dni = textDniEscribano.getText().trim();
        String nombre = textNombreEscribano.getText().trim();
        String direccion = textDireccionEscribano.getText().trim();
        String telefono1 = textTelofonoEscr.getText().trim();
        String telefono2 = textTelefonoEscr2.getText().trim();
        String nroMatricula = textNroMatriculaEscr4.getText().trim();

        if (dni.isEmpty() || nombre.isEmpty() || direccion.isEmpty()
                || telefono1.isEmpty() || nroMatricula.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete todos los campos obligatorios.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = null;

        try {
            con = Conexion.getConexion();
            con.setAutoCommit(false);

            long dniLong = Long.parseLong(dni);

            // 1) Insertamos en Persona
            String sqlPersona = "INSERT INTO persona (DNI_P, NomyApe_P, Direccion_P, Tipo_P) "
                    + "VALUES (?, ?, ?, 'Escribano')";
            try (java.sql.PreparedStatement psPersona = con.prepareStatement(sqlPersona)) {
                psPersona.setLong(1, dniLong);
                psPersona.setString(2, nombre);
                psPersona.setString(3, direccion);
                psPersona.executeUpdate();
            }

            // 2) Insertamos telefono 1
            String sqlTel = "INSERT INTO telefonos_persona (DNI_P, telefono) VALUES (?, ?)";
            try (java.sql.PreparedStatement psTel = con.prepareStatement(sqlTel)) {
                psTel.setLong(1, dniLong);
                psTel.setString(2, telefono1);
                psTel.executeUpdate();
            }

            // 3) Insertamos telefono 2 si fue ingresado
            if (!telefono2.isEmpty()) {
                try (java.sql.PreparedStatement psTel2 = con.prepareStatement(sqlTel)) {
                    psTel2.setLong(1, dniLong);
                    psTel2.setString(2, telefono2);
                    psTel2.executeUpdate();
                }
            }

            // 4) Insertamos en Escribano
            String sqlEscr = "INSERT INTO escribano (DNI_P_Escribano, Direccion_Estudio_M, Nro_Matricula_E) "
                    + "VALUES (?, ?, ?)";
            try (java.sql.PreparedStatement psEscr = con.prepareStatement(sqlEscr)) {
                psEscr.setLong(1, dniLong);
                psEscr.setString(2, direccion);
                psEscr.setString(3, nroMatricula);
                psEscr.executeUpdate();
            }

            // 5) Insertamos el Contrato
            // Nro_Serie lo generamos automaticamente como combinacion de idPropiedad + dniInquilino
            String nroSerie = "C-" + idPropiedadSeleccionada + "-" + dniInquilino;
            String sqlContrato = "INSERT INTO contrato "
                    + "(Nro_Serie, fechaFirma, fechaOcupacion, fechaDesocupacion, montoMensual, "
                    + "DNI_P_Inquilino_Firma, Nro_Matricula_E_Certifica, id_Prop_Alquilada) "
                    + "VALUES (?, CURDATE(), CURDATE(), DATE_ADD(CURDATE(), INTERVAL 1 YEAR), ?, ?, ?, ?)";
            try (java.sql.PreparedStatement psCont = con.prepareStatement(sqlContrato)) {
                psCont.setString(1, nroSerie);
                psCont.setFloat(2, valorMensualPropiedad);
                psCont.setLong(3, dniInquilino);
                psCont.setString(4, nroMatricula);
                psCont.setInt(5, idPropiedadSeleccionada);
                psCont.executeUpdate();
            }

            // 6) Actualizamos la propiedad: ya no está disponible en alquiler
            String sqlProp = "UPDATE propiedades SET en_Alquiler = 0 WHERE id_Prop = ?";
            try (java.sql.PreparedStatement psProp = con.prepareStatement(sqlProp)) {
                psProp.setInt(1, idPropiedadSeleccionada);
                psProp.executeUpdate();
            }

            con.commit();
            JOptionPane.showMessageDialog(this, "Esribano creado correctamente\n");

            JOptionPane.showMessageDialog(this,"Se a creado el Contrato\n","Puede ver el contrato en la seccion CONTRATOS",JOptionPane.INFORMATION_MESSAGE);

            Alquileres ventanaAlquileres = new Alquileres();
            ventanaAlquileres.setLocationRelativeTo(null);
            ventanaAlquileres.setVisible(true);
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El DNI debe ser un número válido.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);

        } catch (SQLException ex) {
            if (con != null) {
                try {
                    con.rollback();
                } catch (SQLException rollbackEx) {
                    logger.log(java.util.logging.Level.SEVERE, "Error en rollback", rollbackEx);
                }
            }
            JOptionPane.showMessageDialog(this,
                    "Error al registrar escribano: " + ex.getMessage(),
                    "Error BD",
                    JOptionPane.ERROR_MESSAGE);

        } finally {
            if (con != null) {
                try {
                    con.setAutoCommit(true);
                } catch (SQLException e) {
                    logger.log(java.util.logging.Level.SEVERE, "Error restaurando autocommit", e);
                }
            }
        }
    }//GEN-LAST:event_btnCargaEscribanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IngresoEscribano().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargaEscribano;
    private javax.swing.JButton btnEcribanoExistente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textDireccionEscribano;
    private javax.swing.JTextField textDniEscribano;
    private javax.swing.JTextField textNombreEscribano;
    private javax.swing.JTextField textNroMatriculaEscr4;
    private javax.swing.JTextField textTelefonoEscr2;
    private javax.swing.JTextField textTelofonoEscr;
    // End of variables declaration//GEN-END:variables
}
