/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inmobiliaria.bd;

/**
 *
 * @author maria
 */
public class IngresoEscribano extends javax.swing.JPanel {

    /**
     * Creates new form IngresoEscribano
     */
    public IngresoEscribano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textDniEscribano = new javax.swing.JTextField();
        textNombreEscribano = new javax.swing.JTextField();
        textDireccionEscribano = new javax.swing.JTextField();
        textTelefonoEscr2 = new javax.swing.JTextField();
        textNroMatriculaEscr4 = new javax.swing.JTextField();
        textTelofonoEscr = new javax.swing.JTextField();
        btnCargaEscribano = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresar Datos del Escribano");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nro de Matricula:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre y  Apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono/s:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, 20));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DNI:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 20));

        textDniEscribano.addActionListener(this::textDniEscribanoActionPerformed);
        add(textDniEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, -1));

        textNombreEscribano.addActionListener(this::textNombreEscribanoActionPerformed);
        add(textNombreEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 250, -1));

        textDireccionEscribano.addActionListener(this::textDireccionEscribanoActionPerformed);
        add(textDireccionEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, -1));

        textTelefonoEscr2.addActionListener(this::textTelefonoEscr2ActionPerformed);
        add(textTelefonoEscr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, -1));

        textNroMatriculaEscr4.addActionListener(this::textNroMatriculaEscr4ActionPerformed);
        add(textNroMatriculaEscr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, -1));

        textTelofonoEscr.addActionListener(this::textTelofonoEscrActionPerformed);
        add(textTelofonoEscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 250, -1));

        btnCargaEscribano.setText("CargarEscribano");
        add(btnCargaEscribano, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -90, 550, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void textDniEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniEscribanoActionPerformed

    private void textNombreEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreEscribanoActionPerformed

    private void textDireccionEscribanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionEscribanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionEscribanoActionPerformed

    private void textTelefonoEscr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoEscr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoEscr2ActionPerformed

    private void textNroMatriculaEscr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNroMatriculaEscr4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNroMatriculaEscr4ActionPerformed

    private void textTelofonoEscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelofonoEscrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelofonoEscrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargaEscribano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textDireccionEscribano;
    private javax.swing.JTextField textDniEscribano;
    private javax.swing.JTextField textNombreEscribano;
    private javax.swing.JTextField textNroMatriculaEscr4;
    private javax.swing.JTextField textTelefonoEscr2;
    private javax.swing.JTextField textTelofonoEscr;
    // End of variables declaration//GEN-END:variables
}
