/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inmobiliaria.bd;

/**
 *
 * @author maria
 */
public class PropiedadesData extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadesData
     */
    public PropiedadesData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        tablaPropiedades = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnIngresoInquilino = new javax.swing.JButton();
        fondoborroso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVolver1 = new javax.swing.JButton();
        tablaPropiedades1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnIngresoInquilino1 = new javax.swing.JButton();
        fondoborroso1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setToolTipText("Alquiler Propiedades");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPropiedades.setViewportView(jTable1);

        add(tablaPropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 470, 330));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione la propiedad");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        btnIngresoInquilino.setText("Ingresar Inquilino");
        btnIngresoInquilino.addActionListener(this::btnIngresoInquilinoActionPerformed);
        add(btnIngresoInquilino, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        fondoborroso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        add(fondoborroso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(this::btnVolver1ActionPerformed);
        jPanel1.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPropiedades1.setViewportView(jTable2);

        jPanel1.add(tablaPropiedades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 470, 330));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seleccione la propiedad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        btnIngresoInquilino1.setText("Ingresar Inquilino");
        btnIngresoInquilino1.addActionListener(this::btnIngresoInquilino1ActionPerformed);
        jPanel1.add(btnIngresoInquilino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        fondoborroso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondoborroso 1.png"))); // NOI18N
        jPanel1.add(fondoborroso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresoInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoInquilinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoInquilinoActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnIngresoInquilino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoInquilino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoInquilino1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoInquilino;
    private javax.swing.JButton btnIngresoInquilino1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel fondoborroso;
    private javax.swing.JLabel fondoborroso1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tablaPropiedades;
    private javax.swing.JScrollPane tablaPropiedades1;
    // End of variables declaration//GEN-END:variables
}
